### ISSUE TITLE
How to create the schema.graphql file ?

### ISSUE THREAD

**Issue by iangregsondev** [kamilkisiela/graphql-config#308]
Hi,

I wonder if anyone can help ? I know this format is used by other programs but I am just wanting to create a schema file from an endpoint.

I have the following

```
projects:
  blog:
    schemaPath: schema.graphql
    extensions:
      endpoints:
        default: "http://localhost:3000/___graphql"
```

Is there some kind of util to create this schema.graphql file ?
