### ISSUE TITLE
[v3] how to set authorization headers?

### ISSUE THREAD

**Issue by waterdrop01** [kamilkisiela/graphql-config#566]
Hello,
my schema: is an endpoint, protexted by an auth mechanism (reading a key in the header).
Before (in v2 & `.graphqlconfig`) I could specify a "headers" key.
What is the recommended new approach?
Thanks

**Comment by dotansimha** [comment]
Hi @waterdrop01 ! 
You should be able to do it this way:

```yaml
schema:
  - http://my-server/graphql:
      headers:
        Authorization: KEY_HERE
```

Note that spacing is important in YAML files - so try to make sure it matches the example.
